-- Croatia Explorer — reference data seed.
-- Run in the Supabase SQL editor AFTER schema.sql. Idempotent (ON CONFLICT (id) DO NOTHING).
-- Counts: 9 types, 21 counties, 63 cities, 204 default POIs.

insert into public.poi_types (id, label, sort_order) values
  ('city', 'City / Town', 0),
  ('mountain', 'Mountain', 1),
  ('lake', 'Lake', 2),
  ('river', 'River', 3),
  ('national_park', 'National Park', 4),
  ('nature', 'Nature / Park', 5),
  ('island', 'Island', 6),
  ('campsite', 'Campsite', 7),
  ('landmark', 'Landmark', 8)
on conflict (id) do nothing;

insert into public.counties (id, name) values
  ('zagreb-county', 'Zagreb County'),
  ('zagreb-city', 'City of Zagreb'),
  ('krapina-zagorje', 'Krapina-Zagorje'),
  ('sisak-moslavina', 'Sisak-Moslavina'),
  ('karlovac', 'Karlovac County'),
  ('varazdin', 'Varaždin County'),
  ('koprivnica-krizevci', 'Koprivnica-Križevci'),
  ('bjelovar-bilogora', 'Bjelovar-Bilogora'),
  ('primorje-gorski-kotar', 'Primorje-Gorski Kotar'),
  ('lika-senj', 'Lika-Senj'),
  ('virovitica-podravina', 'Virovitica-Podravina'),
  ('pozega-slavonia', 'Požega-Slavonia'),
  ('brod-posavina', 'Brod-Posavina'),
  ('zadar', 'Zadar County'),
  ('osijek-baranja', 'Osijek-Baranja'),
  ('sibenik-knin', 'Šibenik-Knin'),
  ('vukovar-srijem', 'Vukovar-Srijem'),
  ('split-dalmatia', 'Split-Dalmatia'),
  ('istria', 'Istria County'),
  ('dubrovnik-neretva', 'Dubrovnik-Neretva'),
  ('medimurje', 'Međimurje County')
on conflict (id) do nothing;

insert into public.cities (id, county_id, name, lat, lng, importance, description, cover_image) values
  ('zagreb', 'zagreb-city', 'Zagreb', 45.815, 15.982, 1, 'Glavni grad Hrvatske: barokni Gornji grad, živahne kavane, muzeji i tržnica Dolac.', null),
  ('split', 'split-dalmatia', 'Split', 43.5081, 16.4403, 1, 'Živo srce Dalmacije, izraslo u i oko Dioklecijanove rimske palače.', null),
  ('rijeka', 'primorje-gorski-kotar', 'Rijeka', 45.3271, 14.4422, 1, 'Najveća hrvatska luka i Europska prijestolnica kulture 2020. na Kvarneru.', null),
  ('osijek', 'osijek-baranja', 'Osijek', 45.555, 18.6955, 1, 'Zelena slavonska metropola na Dravi, poznata po baroknoj Tvrđi.', null),
  ('zadar', 'zadar', 'Zadar', 44.1194, 15.2314, 1, 'Drevni grad na moru, dom Morskih orgulja i jednog od najljepših zalazaka sunca.', null),
  ('dubrovnik', 'dubrovnik-neretva', 'Dubrovnik', 42.6507, 18.0944, 1, '''Biser Jadrana'': grad-tvrđava od blistavog kamena pod zaštitom UNESCO-a.', null),
  ('pula', 'istria', 'Pula', 44.8666, 13.8496, 1, 'Najveći istarski grad, okružen jednim od najočuvanijih rimskih amfiteatara.', null),
  ('sibenik', 'sibenik-knin', 'Šibenik', 43.735, 15.895, 2, 'Dalmatinski grad strmih kamenih ulica i UNESCO katedrale sv. Jakova.', null),
  ('varazdin', 'varazdin', 'Varaždin', 46.3057, 16.3366, 2, 'Barokni biser i nekadašnja prijestolnica, s bijelim Starim gradom.', null),
  ('karlovac', 'karlovac', 'Karlovac', 45.4929, 15.5553, 2, 'Grad na četiri rijeke, izgrađen u obliku zvijezde, vrata gorja i mora.', null),
  ('rovinj', 'istria', 'Rovinj', 45.0812, 13.6384, 2, 'Najromantičniji istarski grad; šarene se kuće spuštaju moru pod crkvom sv. Eufemije.', null),
  ('porec', 'istria', 'Poreč', 45.2272, 13.5947, 2, 'Obalni grad rimskog rastera, poznat po zlatnim mozaicima Eufrazijeve bazilike.', null),
  ('sisak', 'sisak-moslavina', 'Sisak', 45.4851, 16.3734, 2, 'Povijesni grad na ušću Kupe u Savu, s trokutastom renesansnom tvrđavom.', null),
  ('slavonski-brod', 'brod-posavina', 'Slavonski Brod', 45.1631, 18.0142, 2, 'Posavski grad koji čuva jednu od najvećih baroknih tvrđava u Europi.', null),
  ('vukovar', 'vukovar-srijem', 'Vukovar', 45.3491, 19.0031, 2, 'Dunavski grad sjećanja i obnove, s baroknom jezgrom koja oživljava.', null),
  ('cakovec', 'medimurje', 'Čakovec', 46.3844, 16.4339, 2, 'Središte Međimurja, oko renesansnog Staroga grada obitelji Zrinski.', null),
  ('gospic', 'lika-senj', 'Gospić', 44.5461, 15.3748, 2, 'Glavni grad ličke visoravni, polazište za Velebit i zavičaj Nikole Tesle.', null),
  ('knin', 'sibenik-knin', 'Knin', 44.0333, 16.1961, 2, 'Grad pod velikom srednjovjekovnom tvrđavom, nekoć sjedište hrvatskih kraljeva.', null),
  ('bjelovar', 'bjelovar-bilogora', 'Bjelovar', 45.8988, 16.8424, 2, 'Planski građen garnizonski grad 18. stoljeća s velikim središnjim trgom.', null),
  ('koprivnica', 'koprivnica-krizevci', 'Koprivnica', 46.1628, 16.8314, 2, 'Podravski grad biciklizma, dom tvrtke Podravka i naivne umjetnosti.', null),
  ('pozega', 'pozega-slavonia', 'Požega', 45.3403, 17.6853, 2, 'Grad ''Zlatne doline'' s baroknim crkvama u srcu slavonskih vinograda.', null),
  ('virovitica', 'virovitica-podravina', 'Virovitica', 45.8317, 17.3856, 2, 'Slavonski grad na Dravi, poznat po obnovljenom dvorcu Pejačević.', null),
  ('krapina', 'krapina-zagorje', 'Krapina', 46.1608, 15.8789, 2, 'Zagorski grad uz svjetski poznato nalazište i muzej krapinskih neandertalaca.', null),
  ('velika-gorica', 'zagreb-county', 'Velika Gorica', 45.7133, 16.0725, 2, 'Grad Turopolja južno od Zagreba, uz Zračnu luku Franjo Tuđman.', null),
  ('dakovo', 'osijek-baranja', 'Đakovo', 45.3081, 18.4111, 2, 'Grad veličanstvene katedrale biskupa Strossmayera i uzgoja lipicanaca.', null),
  ('samobor', 'zagreb-county', 'Samobor', 45.8021, 15.7118, 3, 'Ljupki izletnički gradić kraj Zagreba, poznat po kremšnitama.', null),
  ('jastrebarsko', 'zagreb-county', 'Jastrebarsko', 45.6714, 15.6517, 3, 'Jaska u podnožju Plešivice, poznata po pjenušcima i dvorcu Erdödy.', null),
  ('marija-bistrica', 'krapina-zagorje', 'Marija Bistrica', 46.0028, 16.1186, 3, 'Najveće hrvatsko marijansko svetište i hodočasničko središte Zagorja.', null),
  ('zabok', 'krapina-zagorje', 'Zabok', 46.0292, 15.9122, 3, 'Prometno i gospodarsko središte Krapinsko-zagorske županije.', null),
  ('kutina', 'sisak-moslavina', 'Kutina', 45.4822, 16.7811, 3, 'Središte Moslavine uz Park prirode Lonjsko polje.', null),
  ('ogulin', 'karlovac', 'Ogulin', 45.2661, 15.2239, 3, 'Grad bajki pod Klekom, zavičaj Ivane Brlić-Mažuranić.', null),
  ('slunj', 'karlovac', 'Slunj', 45.1169, 15.5878, 3, 'Gradić nad slapovima Slunjčice i slikovitim mlinicama Rastoka.', null),
  ('ivanec', 'varazdin', 'Ivanec', 46.2239, 16.1217, 3, 'Grad u podnožju Ivanščice na sjeverozapadu Hrvatske.', null),
  ('krizevci', 'koprivnica-krizevci', 'Križevci', 46.0225, 16.5422, 3, 'Stari podravski grad barokne arhitekture i tradicije Križevačkog spravišča.', null),
  ('daruvar', 'bjelovar-bilogora', 'Daruvar', 45.5922, 17.225, 3, 'Toplički grad poznat po termama, vinima i češkoj manjini.', null),
  ('opatija', 'primorje-gorski-kotar', 'Opatija', 45.3376, 14.3052, 3, 'Lječilište belle époque s raskošnim vilama i 12 km dugom šetnicom Lungomare.', null),
  ('krk', 'primorje-gorski-kotar', 'Krk', 45.0259, 14.5731, 3, 'Stari grad koji je dao ime najvećem hrvatskom otoku, mostom povezanom s kopnom.', null),
  ('cres', 'primorje-gorski-kotar', 'Cres', 44.9612, 14.4079, 3, 'Stari kvarnerski gradić na otoku bjeloglavih supova i slatkovodnog Vranskog jezera.', null),
  ('mali-losinj', 'primorje-gorski-kotar', 'Mali Lošinj', 44.5317, 14.4683, 3, 'Najveći otočni grad, ''otok vitalnosti'' s borovom uvalom Čikat.', null),
  ('senj', 'lika-senj', 'Senj', 44.9894, 14.9058, 3, 'Vjetroviti primorski grad uskoka, pod tvrđavom Nehaj.', null),
  ('novalja', 'lika-senj', 'Novalja', 44.5562, 14.8842, 3, 'Ljetovalište na otoku Pagu, poznato po plaži Zrće i noćnom životu.', null),
  ('slatina', 'virovitica-podravina', 'Slatina', 45.7025, 17.7022, 3, 'Podravski grad parkova i dvoraca na rubu Papuka.', null),
  ('pakrac', 'pozega-slavonia', 'Pakrac', 45.4372, 17.1894, 3, 'Zapadnoslavonski grad koji se obnavlja, između Psunja i Papuka.', null),
  ('nova-gradiska', 'brod-posavina', 'Nova Gradiška', 45.2536, 17.3828, 3, 'Posavski grad u podnožju Psunja, uz Savu i autocestu.', null),
  ('nasice', 'osijek-baranja', 'Našice', 45.4922, 18.0908, 3, 'Slavonski grad oko dvorca Pejačević, na obroncima Krndije.', null),
  ('vinkovci', 'vukovar-srijem', 'Vinkovci', 45.2878, 18.8058, 3, 'Jedan od najstarijih neprekidno naseljenih gradova u Europi, u srcu Slavonije.', null),
  ('ilok', 'vukovar-srijem', 'Ilok', 45.2239, 19.3708, 3, 'Najistočniji hrvatski grad, dunavsko vinsko središte oko dvorca Odescalchi.', null),
  ('biograd', 'zadar', 'Biograd na Moru', 43.9376, 15.4419, 3, 'Nekadašnja hrvatska kraljevska luka, danas ljetovalište i marina.', null),
  ('nin', 'zadar', 'Nin', 44.2406, 15.1808, 3, 'Najstariji hrvatski kraljevski grad na otočiću, okružen plitkim pješčanim plažama.', null),
  ('pag', 'zadar', 'Pag', 44.4447, 15.0561, 3, 'Grad na ''mjesečevom'' otoku, poznat po paškom siru, čipki i soli.', null),
  ('vodice', 'sibenik-knin', 'Vodice', 43.7547, 15.7794, 3, 'Popularno šibensko ljetovalište živahne rive i noćnog života.', null),
  ('skradin', 'sibenik-knin', 'Skradin', 43.8172, 15.9228, 3, 'Ljupki gradić na rijeci Krki i polazište za njezine slapove.', null),
  ('trogir', 'split-dalmatia', 'Trogir', 43.5164, 16.2502, 3, 'UNESCO otok-grad uskih kamenih uličica s vrhunskim portalom katedrale.', null),
  ('makarska', 'split-dalmatia', 'Makarska', 43.2936, 17.0197, 3, 'Živahno ljetovalište u uvali s palmama pod moćnim Biokovom.', null),
  ('omis', 'split-dalmatia', 'Omiš', 43.4442, 16.6886, 3, 'Nekadašnje gusarsko uporište gdje kanjon Cetine izbija na more.', null),
  ('hvar', 'split-dalmatia', 'Hvar', 43.1729, 16.4428, 3, 'Glamurozni otočni grad s najvećim trgom u Dalmaciji i tvrđavom Fortica.', null),
  ('metkovic', 'dubrovnik-neretva', 'Metković', 43.0542, 17.6483, 3, 'Grad u delti Neretve, poznat po mandarinama i ornitološkom rezervatu.', null),
  ('korcula', 'dubrovnik-neretva', 'Korčula', 42.9614, 17.1356, 3, 'Utvrđeni grad na otoku Korčuli, po legendi rodno mjesto Marka Pola.', null),
  ('ston', 'dubrovnik-neretva', 'Ston', 42.8394, 17.6961, 3, 'Vrata Pelješca, poznata po najduljim zidinama Europe, solani i kamenicama.', null),
  ('umag', 'istria', 'Umag', 45.4375, 13.5244, 3, 'Najzapadniji hrvatski grad, istarsko središte tenisa i maslinova ulja.', null),
  ('motovun', 'istria', 'Motovun', 45.3367, 13.8281, 3, 'Utvrđeni gradić na brdu iznad doline Mirne, poznat po tartufima i festivalu.', null),
  ('pazin', 'istria', 'Pazin', 45.2403, 13.9389, 3, 'Središte istarske unutrašnjosti, nad ponorom koji je nadahnuo Julesa Vernea.', null),
  ('prelog', 'medimurje', 'Prelog', 46.3422, 16.6139, 3, 'Drugi grad Međimurja, uz rijeku Dravu i njezina jezera.', null)
on conflict (id) do nothing;

insert into public.pois (id, owner_id, county_id, city_id, name, type, description, lat, lng) values
  ('zagreb-city-center', null, 'zagreb-city', 'zagreb', 'Zagreb Old Town', 'city', 'Baroque upper town, Dolac market, Cathedral', null, null),
  ('zagreb-medvednica', null, 'zagreb-city', null, 'Medvednica Mountain', 'mountain', 'Mountain park above Zagreb, Sljeme peak 1033m', 45.8994, 15.9472),
  ('zagreb-jarun', null, 'zagreb-city', 'zagreb', 'Jarun Lake', 'lake', 'Recreational lake in Zagreb, rowing & swimming', null, null),
  ('zagreb-maksimir', null, 'zagreb-city', 'zagreb', 'Maksimir Park', 'nature', 'Oldest public park in SE Europe, 316ha', null, null),
  ('zagreb-bundek', null, 'zagreb-city', 'zagreb', 'Bundek Lake', 'lake', 'City lake with beaches and playgrounds', null, null),
  ('zagreb-lotrscak', null, 'zagreb-city', 'zagreb', 'Lotrščak Tower', 'landmark', 'Medieval tower with cannon fired daily at noon', null, null),
  ('samobor-town', null, 'zagreb-county', 'samobor', 'Samobor', 'city', 'Charming town known for kremsnita cake', null, null),
  ('samobor-gorje', null, 'zagreb-county', null, 'Samoborsko Gorje', 'mountain', 'Low mountain range near Samobor', 45.7594, 15.6883),
  ('zumberak', null, 'zagreb-county', null, 'Žumberak Nature Park', 'nature', 'Green hills, old villages, wolves and bears', 45.7833, 15.4667),
  ('velika-gorica', null, 'zagreb-county', 'velika-gorica', 'Velika Gorica', 'city', 'Town near Zagreb airport', null, null),
  ('turopolje', null, 'zagreb-county', null, 'Turopolje', 'nature', 'Traditional oak forests, old wooden churches', 45.65, 16.15),
  ('krapina-neanderthal', null, 'krapina-zagorje', 'krapina', 'Krapina Neanderthal Museum', 'landmark', 'World-class prehistoric site with Neanderthal bones', null, null),
  ('trakoscan-castle', null, 'krapina-zagorje', null, 'Trakošćan Castle', 'landmark', 'Romantic 13th-century castle above a lake', 46.2536, 15.9511),
  ('trakoscan-lake', null, 'krapina-zagorje', null, 'Trakošćan Lake', 'lake', 'Serene artificial lake beside the castle', 46.2625, 15.9442),
  ('pregrada', null, 'krapina-zagorje', null, 'Pregrada', 'city', 'Small Zagorje town with a beautiful church', 46.1628, 15.7511),
  ('kumrovec', null, 'krapina-zagorje', null, 'Kumrovec Ethnological Museum', 'landmark', 'Open-air village museum, birthplace of Tito', 46.0744, 15.6769),
  ('klanjec', null, 'krapina-zagorje', null, 'Klanjec', 'city', 'Town with Antun Augustinčić gallery', 46.0494, 15.7331),
  ('sutinska-vrela', null, 'krapina-zagorje', null, 'Sutinska Vrela Spa', 'nature', 'Thermal spring resort in Zagorje hills', 46.1156, 15.8953),
  ('varazdin-old-town', null, 'varazdin', 'varazdin', 'Varaždin Old Town', 'city', 'Baroque city, well-preserved medieval castle', null, null),
  ('varazdin-castle', null, 'varazdin', 'varazdin', 'Varaždin Castle', 'landmark', 'Well-preserved fortress now a city museum', null, null),
  ('varazdin-cemetery', null, 'varazdin', 'varazdin', 'Varaždin Cemetery', 'landmark', 'One of Europe''s most beautiful cemeteries, a park-museum', null, null),
  ('varazdin-toplice', null, 'varazdin', null, 'Varaždinske Toplice', 'nature', 'Roman thermal baths still active today', 46.21, 16.4214),
  ('koprivnica-city', null, 'koprivnica-krizevci', 'koprivnica', 'Koprivnica', 'city', 'Podravina market town, known for Podravka food company', null, null),
  ('hlebine-naive-art', null, 'koprivnica-krizevci', null, 'Hlebine Gallery', 'landmark', 'Village birthplace of Croatian naive art movement', 46.1558, 16.9669),
  ('đurđevac-castle', null, 'koprivnica-krizevci', null, 'Đurđevac Old Town', 'landmark', 'Medieval fortress, legend of the Picok', 46.0422, 17.0697),
  ('krizevci-city', null, 'koprivnica-krizevci', 'krizevci', 'Križevci', 'city', 'Town with beautiful Baroque architecture', null, null),
  ('bjelovar-city', null, 'bjelovar-bilogora', 'bjelovar', 'Bjelovar', 'city', 'Grid-planned 18th century garrison town', null, null),
  ('bilogora-forest', null, 'bjelovar-bilogora', null, 'Bilogora Hills', 'mountain', 'Forested ridge, wine growing area', 45.9083, 16.9917),
  ('daruvar-spa', null, 'bjelovar-bilogora', 'daruvar', 'Daruvar Spa Town', 'nature', 'Roman thermal springs, Czech minority heritage', null, null),
  ('sisak-fortress', null, 'sisak-moslavina', 'sisak', 'Sisak Fortress', 'landmark', 'Renaissance fortress, famous 1593 battle site', null, null),
  ('lonjsko-polje', null, 'sisak-moslavina', null, 'Lonjsko Polje Nature Park', 'nature', 'Largest floodplain in Europe, white storks, old villages', 45.4131, 16.7456),
  ('kutina-city', null, 'sisak-moslavina', 'kutina', 'Kutina', 'city', 'Moslavina regional center', null, null),
  ('jasenovac-memorial', null, 'sisak-moslavina', null, 'Jasenovac Memorial', 'landmark', 'WWII memorial site of great historical significance', 45.2794, 16.9283),
  ('karlovac-city', null, 'karlovac', 'karlovac', 'Karlovac', 'city', 'Star-shaped Renaissance town, four rivers confluence', null, null),
  ('korana-river', null, 'karlovac', null, 'Korana River', 'river', 'Crystal-clear karst river, ideal for kayaking', 45.1417, 15.5878),
  ('mrežnica-river', null, 'karlovac', null, 'Mrežnica River', 'river', 'River with travertine waterfalls and swimming holes', 45.4414, 15.5036),
  ('slunj-rastoke', null, 'karlovac', null, 'Rastoke (Little Plitvice)', 'nature', 'Watermills and waterfalls where Slunjčica meets Korana', 45.1208, 15.5861),
  ('risnjak-np', null, 'karlovac', null, 'Risnjak National Park', 'national_park', 'Pristine mountain forests, lynx habitat', 45.4303, 14.6186),
  ('ogulin-city', null, 'karlovac', 'ogulin', 'Ogulin', 'city', 'Town of fairy tales, home of Ivana Brlić-Mažuranić', null, null),
  ('rijeka-city', null, 'primorje-gorski-kotar', 'rijeka', 'Rijeka', 'city', 'Croatia''s largest port, European Capital of Culture 2020', null, null),
  ('opatija-riviera', null, 'primorje-gorski-kotar', 'opatija', 'Opatija Riviera', 'city', 'Habsburg-era resort town, lungomare promenade', null, null),
  ('ucka-mountain', null, 'primorje-gorski-kotar', null, 'Učka Nature Park', 'mountain', 'Mountain above Opatija Riviera, 1401m Vojak peak', 45.2914, 14.2014),
  ('kvarner-gulf', null, 'primorje-gorski-kotar', null, 'Kvarner Gulf', 'nature', 'Large sheltered bay with islands Krk, Cres, Lošinj, Rab', 44.9, 14.3),
  ('krk-island', null, 'primorje-gorski-kotar', 'krk', 'Krk Island', 'island', 'Largest Croatian island, connected by bridge to mainland', null, null),
  ('cres-island', null, 'primorje-gorski-kotar', null, 'Cres Island', 'island', 'Wild island with griffon vultures and Vrana Lake', 44.96, 14.41),
  ('losinj-island', null, 'primorje-gorski-kotar', null, 'Lošinj Island', 'island', '''Island of vitality'', dolphins in the bay', 44.57, 14.42),
  ('gorski-kotar', null, 'primorje-gorski-kotar', null, 'Gorski Kotar Highlands', 'mountain', 'Green mountain region, bears and wolves, Risnjak & Snježnik', 45.4, 14.75),
  ('camp-krk', null, 'primorje-gorski-kotar', null, 'Camp Krk (Politin)', 'campsite', 'Family campsite on Krk island, pebble beach', 45.0218, 14.5824),
  ('camp-kovačine', null, 'primorje-gorski-kotar', null, 'Camp Kovačine, Cres', 'campsite', 'Naturist camp on Cres with olive groves', 44.9629, 14.397),
  ('plitvice-lakes', null, 'lika-senj', null, 'Plitvice Lakes NP', 'national_park', 'UNESCO site, 16 terraced lakes with spectacular waterfalls', 44.8806, 15.6167),
  ('velebit-north', null, 'lika-senj', null, 'Sjeverni Velebit NP', 'national_park', 'Northern Velebit, Hajdučki kukovi rock formations', 44.8142, 14.9753),
  ('paklenica-np', null, 'lika-senj', null, 'Paklenica NP', 'national_park', 'Spectacular gorges, rock climbing mecca', 44.3167, 15.4333),
  ('senj-nehaj', null, 'lika-senj', 'senj', 'Senj & Nehaj Fortress', 'landmark', 'Uskok pirate town, dramatic coastal fortress', null, null),
  ('gospic-city', null, 'lika-senj', 'gospic', 'Gospić', 'city', 'Lika regional center, Nikola Tesla Museum nearby', null, null),
  ('plitvicka-jezera-village', null, 'lika-senj', null, 'Plitvička Jezera Village', 'city', 'Gateway village to Plitvice NP', 44.8814, 15.6224),
  ('velebit-mountain', null, 'lika-senj', null, 'Velebit Mountain', 'mountain', 'Longest Croatian mountain range, 145km, 1757m Vaganski vrh', 44.5361, 15.4208),
  ('camp-korana-plitvice', null, 'lika-senj', null, 'Camp Korana Plitvice', 'campsite', 'Campsite on Korana river near Plitvice Lakes', 44.9511, 15.6417),
  ('virovitica-city', null, 'virovitica-podravina', 'virovitica', 'Virovitica', 'city', 'Slavonian town with baroque church and park', null, null),
  ('orahovica-park', null, 'virovitica-podravina', null, 'Orahovica', 'city', 'Town near Ružica Fortress ruins', 45.5292, 17.8875),
  ('papuk-geopark', null, 'virovitica-podravina', null, 'Papuk Nature Park', 'mountain', 'Geopark with waterfalls and Ružica Castle', 45.5256, 17.6017),
  ('pozega-city', null, 'pozega-slavonia', 'pozega', 'Požega', 'city', 'The Golden Valley, baroque churches, wine region', null, null),
  ('kutjevo-winery', null, 'pozega-slavonia', null, 'Kutjevo Winery', 'landmark', 'One of Croatia''s oldest wineries, Cistercian founded 1232', 45.4364, 17.8817),
  ('slavonski-brod-city', null, 'brod-posavina', 'slavonski-brod', 'Slavonski Brod', 'city', 'River town with largest baroque fortress in Croatia', null, null),
  ('brod-fortress', null, 'brod-posavina', 'slavonski-brod', 'Brod Fortress', 'landmark', '18th-century star-shaped fortress on the Sava river', null, null),
  ('osijek-city', null, 'osijek-baranja', 'osijek', 'Osijek', 'city', 'Slavonian capital, tvrđa baroque fortress-town', null, null),
  ('osijek-tvrdja', null, 'osijek-baranja', 'osijek', 'Osijek Tvrđa', 'landmark', 'Best-preserved baroque fortress in Central Europe', null, null),
  ('kopacki-rit', null, 'osijek-baranja', null, 'Kopački Rit Nature Park', 'nature', 'Floodplain wetland, Europe''s largest bird sanctuary', 45.5994, 18.7892),
  ('baranja-region', null, 'osijek-baranja', null, 'Baranja Wine Region', 'nature', 'Pannonian plains with Graševina white wine', 45.75, 18.7),
  ('bilje-castle', null, 'osijek-baranja', null, 'Bilje (Prince Eugene Castle)', 'landmark', 'Estate of Prince Eugene of Savoy', 45.5894, 18.7369),
  ('vukovar-city', null, 'vukovar-srijem', 'vukovar', 'Vukovar', 'city', 'City of remembrance, Danube-side, powerful war memorial', null, null),
  ('vukovar-water-tower', null, 'vukovar-srijem', 'vukovar', 'Vukovar Water Tower', 'landmark', 'Symbol of Croatian resilience and independence', null, null),
  ('ilok-city', null, 'vukovar-srijem', 'ilok', 'Ilok', 'city', 'Easternmost Croatian town, Odescalchi Castle, wine cellars', null, null),
  ('vinkovci-city', null, 'vukovar-srijem', 'vinkovci', 'Vinkovci', 'city', 'One of Europe''s oldest continuously inhabited towns', null, null),
  ('zadar-old-town', null, 'zadar', 'zadar', 'Zadar Old Town', 'city', 'Roman forum, Sea Organ, Greeting to the Sun', null, null),
  ('vrana-lake', null, 'zadar', null, 'Vrana Lake', 'lake', 'Croatia''s largest natural lake, flamingos spotted', 43.8906, 15.5794),
  ('pag-island', null, 'zadar', null, 'Pag Island', 'island', 'Moonscape island, Paški sir cheese, lace, nightlife', 44.45, 15.05),
  ('nin-city', null, 'zadar', 'nin', 'Nin', 'city', 'Oldest Croatian royal town, sandy Zaton beach', null, null),
  ('zrmanja-river', null, 'zadar', null, 'Zrmanja Canyon', 'river', 'Wild river canyon, white-water rafting', 44.2014, 15.7764),
  ('novigrad-sea', null, 'zadar', null, 'Novigrad on the Sea', 'city', 'Small walled coastal town, Novigrad Sea inlet', 44.1833, 15.55),
  ('telascica-nature-park', null, 'zadar', null, 'Telašćica Nature Park', 'nature', 'Bay on Dugi Otok with cliffs and salt lake', 43.8917, 15.1617),
  ('camp-simuni', null, 'zadar', null, 'Camp Šimuni, Pag', 'campsite', 'Award-winning family camp on Pag island', 44.4633, 14.9656),
  ('camp-strasko', null, 'zadar', null, 'Camp Straško, Novalja', 'campsite', 'Largest camp in Croatia, near Zrće beach', 44.5458, 14.8769),
  ('kornati-np', null, 'zadar', null, 'Kornati National Park', 'national_park', 'Archipelago of 89 islands, UNESCO tentative list', 43.8333, 15.25),
  ('sibenik-city', null, 'sibenik-knin', 'sibenik', 'Šibenik', 'city', 'Dalmatian city, St. James Cathedral UNESCO site', null, null),
  ('krka-np', null, 'sibenik-knin', null, 'Krka National Park', 'national_park', 'Travertine waterfalls on the Krka river, Skradinski Buk', 43.8017, 15.9753),
  ('krka-river', null, 'sibenik-knin', null, 'Krka River', 'river', 'Karst river 73km, flows through spectacular canyons', 43.85, 15.96),
  ('drnis-city', null, 'sibenik-knin', null, 'Drniš', 'city', 'Town known for pršut (prosciutto) and Ivan Meštrović', 43.8617, 16.1517),
  ('knin-fortress', null, 'sibenik-knin', 'knin', 'Knin Fortress', 'landmark', 'Largest Croatian fortress, medieval capital of Croatia', null, null),
  ('camp-solaris', null, 'sibenik-knin', null, 'Camp Solaris, Šibenik', 'campsite', 'Premium resort camp near Šibenik', 43.6997, 15.8794),
  ('skradin-town', null, 'sibenik-knin', 'skradin', 'Skradin', 'city', 'Gateway to Krka NP, charming riverside town', null, null),
  ('split-city', null, 'split-dalmatia', 'split', 'Split', 'city', 'Diocletian''s Palace, Croatia''s second city', null, null),
  ('diocletian-palace', null, 'split-dalmatia', 'split', 'Diocletian''s Palace', 'landmark', 'UNESCO Roman palace where 3000 people still live today', null, null),
  ('hvar-island', null, 'split-dalmatia', 'hvar', 'Hvar Island', 'island', 'Lavender fields, sunny riviera, historic town', null, null),
  ('brac-island', null, 'split-dalmatia', null, 'Brač Island', 'island', 'Zlatni Rat beach, white limestone, highest Dalmatian peak', 43.3, 16.65),
  ('vis-island', null, 'split-dalmatia', null, 'Vis Island', 'island', 'Remote unspoiled island, Biševo Blue Cave nearby', 43.04, 16.15),
  ('biokovo-mountain', null, 'split-dalmatia', null, 'Biokovo Nature Park', 'mountain', 'Dramatic karst mountain, 1762m Sveti Jure, skywalk', 43.3414, 17.0506),
  ('cetina-river', null, 'split-dalmatia', 'omis', 'Cetina River Canyon', 'river', 'Rafting and canyoning in stunning gorge above Omiš', null, null),
  ('makarska-riviera', null, 'split-dalmatia', 'makarska', 'Makarska Riviera', 'nature', '30km of beaches under Biokovo mountain', null, null),
  ('trogir-old-town', null, 'split-dalmatia', 'trogir', 'Trogir', 'city', 'UNESCO island town with Romanesque cathedral', null, null),
  ('klis-fortress', null, 'split-dalmatia', 'split', 'Klis Fortress', 'landmark', 'Ancient fortress above Split, Game of Thrones filming', null, null),
  ('camp-skrinja', null, 'split-dalmatia', null, 'Camp Škrinja, Brač', 'campsite', 'Secluded camp on Brač island with crystal water', 43.2833, 16.6333),
  ('omis-city', null, 'split-dalmatia', 'omis', 'Omiš', 'city', 'Pirate fortress town at the mouth of Cetina canyon', null, null),
  ('pula-city', null, 'istria', 'pula', 'Pula', 'city', 'Roman amphitheater, largest in the world still in use', null, null),
  ('rovinj-city', null, 'istria', 'rovinj', 'Rovinj', 'city', 'Romantic Venetian fishing town, colorful seafront houses', null, null),
  ('porec-city', null, 'istria', 'porec', 'Poreč', 'city', 'Euphrasian Basilica UNESCO, Roman cardo street', null, null),
  ('motovun-hill-town', null, 'istria', 'motovun', 'Motovun', 'city', 'Hilltop medieval town surrounded by truffle forests', null, null),
  ('brijuni-np', null, 'istria', null, 'Brijuni National Park', 'national_park', 'Archipelago near Pula, former Tito''s residence, safari', 44.9142, 13.7583),
  ('limski-kanal', null, 'istria', null, 'Lim Fjord', 'nature', 'Drowned river valley, oysters and mussels farmed here', 45.1311, 13.6333),
  ('groznjan-village', null, 'istria', null, 'Grožnjan Artists Village', 'landmark', 'Medieval hilltop village, international music workshops', 45.3783, 13.7208),
  ('istrian-truffles', null, 'istria', null, 'Buzet & Truffle Country', 'nature', 'Istrian interior, world-class black & white truffles', 45.4114, 13.9611),
  ('camp-bi-village', null, 'istria', null, 'Camp Bi Village, Fažana', 'campsite', 'Large resort camp near Brijuni, great facilities', 44.9286, 13.8053),
  ('camp-polari', null, 'istria', null, 'Camp Polari, Rovinj', 'campsite', 'Naturist camp with pinewood and pebble beaches', 45.0617, 13.6714),
  ('vrsar-town', null, 'istria', null, 'Vrsar', 'city', 'Cosanova town on a hill, naturist Koversada camp nearby', 45.1511, 13.6067),
  ('cakovec-medimurje', null, 'medimurje', 'cakovec', 'Čakovec', 'city', 'Capital of Međimurje, Zrinski Castle, medieval old town', null, null),
  ('medimurje-wine', null, 'medimurje', null, 'Međimurje Wine Road', 'nature', 'Picturesque wine-growing hills, Graševina and Škrlet varieties', 46.45, 16.32),
  ('sveti-martin-spa', null, 'medimurje', null, 'Sveti Martin on the Mura', 'nature', 'Wellness resort town on the Mura river', 46.5022, 16.3653),
  ('dubrovnik-city', null, 'dubrovnik-neretva', 'dubrovnik', 'Dubrovnik', 'city', 'Pearl of the Adriatic, walled city, UNESCO World Heritage', null, null),
  ('dubrovnik-walls', null, 'dubrovnik-neretva', 'dubrovnik', 'Dubrovnik City Walls', 'landmark', '2km walkable medieval walls with sea views', null, null),
  ('korcula-island', null, 'dubrovnik-neretva', 'korcula', 'Korčula Island', 'island', 'Medieval walled town, Marco Polo birthplace legend', null, null),
  ('mljet-np', null, 'dubrovnik-neretva', null, 'Mljet National Park', 'national_park', 'Saltwater lakes and Benedictine monastery on an island', 42.7817, 17.3814),
  ('mljet-island', null, 'dubrovnik-neretva', null, 'Mljet Island', 'island', 'Greenest Croatian island, Homer''s Ogygia', 42.75, 17.53),
  ('neretva-delta', null, 'dubrovnik-neretva', null, 'Neretva River Delta', 'river', 'River delta with tangerines, frogs, eels, boat safaris', 43.0111, 17.5311),
  ('lastovo-island', null, 'dubrovnik-neretva', null, 'Lastovo Island', 'island', 'Remote nature park island, stargazing reserve', 42.75, 16.9),
  ('ston-walls', null, 'dubrovnik-neretva', 'ston', 'Ston Walls & Salt Pans', 'landmark', '14th-century walls, longest in Europe, Pelješac oysters', null, null),
  ('peljesac-peninsula', null, 'dubrovnik-neretva', null, 'Pelješac Peninsula', 'nature', 'Dingač wine, sandy beaches, dramatic scenery', 42.93, 17.38),
  ('konavle-valley', null, 'dubrovnik-neretva', null, 'Konavle Valley', 'nature', 'Lush valley behind Dubrovnik, folk costumes, watermills', 42.55, 18.35),
  ('camp-solitudo-dubrovnik', null, 'dubrovnik-neretva', null, 'Camp Solitudo, Dubrovnik', 'campsite', 'Urban camp on Babin Kuk peninsula near Dubrovnik', 42.6617, 18.0711),
  ('pula-arena', null, 'istria', 'pula', 'Pula Arena', 'landmark', 'Best-preserved Roman amphitheatre, still hosts summer concerts', null, null),
  ('pazin-castle', null, 'istria', 'pazin', 'Pazin Castle & Abyss', 'landmark', 'Istria''s largest medieval castle above Jules Verne''s cave abyss', null, null),
  ('rovinj-euphemia', null, 'istria', 'rovinj', 'St. Euphemia Basilica', 'landmark', 'Baroque church crowning Rovinj''s old town, climbable bell tower', null, null),
  ('zadar-forum', null, 'zadar', 'zadar', 'Roman Forum & Sea Organ', 'landmark', 'Ancient forum, St. Donatus rotunda and the wave-powered Sea Organ', null, null),
  ('split-marjan', null, 'split-dalmatia', 'split', 'Marjan Hill', 'nature', 'Forested peninsula park above Split with viewpoints and beaches', null, null),
  ('dubrovnik-lovrijenac', null, 'dubrovnik-neretva', 'dubrovnik', 'Fort Lovrijenac', 'landmark', 'Dramatic clifftop fortress guarding the western walls of Dubrovnik', null, null),
  ('camp-zagreb-rakitje', null, 'zagreb-county', null, 'Camp Zagreb (Rakitje)', 'campsite', 'Autokamp na jezeru Rakitje kraj Svete Nedelje, nadomak Zagreba.', 45.7997, 15.8239),
  ('camp-vita-tuhelj', null, 'krapina-zagorje', null, 'Camp Vita Terme Tuhelj', 'campsite', 'Kamp uz toplice Terme Tuhelj s pristupom velikom vodenom parku.', 46.066, 15.7864),
  ('camp-tradicije-cigoc', null, 'sisak-moslavina', null, 'Kamp Tradicije Čigoč', 'campsite', 'Mali obiteljski kamp u selu roda Čigoč u srcu Lonjskog polja.', 45.4217, 16.6375),
  ('camp-slapic', null, 'karlovac', null, 'Kamp Slapić (Mrežnica)', 'campsite', 'Nagrađivani kamp uz tirkiznu rijeku Mrežnicu u Dugoj Resi.', 45.4422, 15.4983),
  ('camp-korana', null, 'karlovac', null, 'Kamp Korana', 'campsite', 'Prostrani kamp uz kanjon bistre Korane blizu Slunja, baza za Plitvice.', 44.9511, 15.6417),
  ('camp-varazdinske-toplice', null, 'varazdin', null, 'Kamp Varaždinske Toplice', 'campsite', 'Autokamp u najstarijim hrvatskim toplicama uz ljekovitu termalnu vodu.', 46.2111, 16.4253),
  ('camp-vinia', null, 'bjelovar-bilogora', null, 'Kamp Vinia', 'campsite', 'Mali obiteljski kamp uz seosko domaćinstvo i vinariju kraj Bjelovara.', 45.9248, 16.8953),
  ('camp-omisalj', null, 'primorje-gorski-kotar', null, 'Kamp Omišalj', 'campsite', 'Kamp na samom ulazu na otok Krk s pješčanom plažom i bazenom.', 45.2158, 14.5424),
  ('camp-krk-premium', null, 'primorje-gorski-kotar', null, 'Krk Premium Camping Resort', 'campsite', 'Eko-kamp uz povijesni grad Krk, s wellnessom, bazenima i sportskim terenima.', 45.021, 14.5683),
  ('camp-jezevac', null, 'primorje-gorski-kotar', null, 'Ježevac Premium Camping Resort', 'campsite', 'Kamp uz staru jezgru grada Krka, okružen gustom borovom šumom i plažama.', 45.0188, 14.5668),
  ('camp-baska-beach', null, 'primorje-gorski-kotar', null, 'Baška Beach Camping Resort', 'campsite', 'Kamp uz dugu šljunčanu Velu plažu u Baški na otoku Krku.', 44.9656, 14.7478),
  ('camp-slatina-cres', null, 'primorje-gorski-kotar', null, 'Kamp Slatina', 'campsite', 'Kamp na otoku Cresu (Martinšćica), prilagođen boravku s kućnim ljubimcima.', 44.8156, 14.3468),
  ('camp-san-marino-rab', null, 'primorje-gorski-kotar', null, 'San Marino Camping Resort', 'campsite', 'Kamp na otoku Rabu uz čuvenu pješčanu Rajsku plažu, idealan za obitelji.', 44.8142, 14.7578),
  ('camp-slamni', null, 'primorje-gorski-kotar', null, 'Camping Slamni', 'campsite', 'Butik obiteljski kamp u Dobrinju na Krku, uz ljekovito blato uvale Soline.', 45.1533, 14.6177),
  ('camp-cikat', null, 'primorje-gorski-kotar', null, 'Kamp Čikat', 'campsite', 'Kamp u borovoj šumi uvale Čikat na Lošinju, s aquaparkom i obiteljskim sadržajem.', 44.5358, 14.4469),
  ('camp-poljana', null, 'primorje-gorski-kotar', null, 'Camping Baia Holiday Poljana', 'campsite', 'Kamp na najužem dijelu otoka Lošinja, okružen morem s obiju strana.', 44.5555, 14.4421),
  ('camp-jankovac', null, 'virovitica-podravina', null, 'Planinski kamp Jankovac', 'campsite', 'Planinski eko-kamp na Papuku kod izletišta Jankovac, uz slapove i staze.', 45.5214, 17.6842),
  ('camp-duboka', null, 'pozega-slavonia', null, 'Eko-kamp Duboka (Velika)', 'campsite', 'Prvi eko-kamp kontinentalne Hrvatske, na južnim padinama Papuka u Velikoj.', 45.4656, 17.6611),
  ('camp-petnja', null, 'brod-posavina', null, 'Kamp Petnja', 'campsite', 'Mirni kamp uz slikovito jezero Petnja pod Dilj gorom, omiljen kod ribolovaca.', 45.1956, 17.9514),
  ('camp-plitvice-holiday', null, 'lika-senj', null, 'Plitvice Holiday Resort', 'campsite', 'Kamp i resort blizu Plitvica s glampingom u kućicama na drveću i jezeru.', 44.9733, 15.6444),
  ('camp-big-bear-plitvice', null, 'lika-senj', null, 'Big Bear Plitvice Resort', 'campsite', 'Ugodan butik kamp u prirodi petnaestak minuta od Plitvičkih jezera.', 44.8725, 15.4958),
  ('camp-suza-baranje', null, 'osijek-baranja', null, 'Kamp Suza Baranje', 'campsite', 'Mali gostoljubivi kamp u baranjskom selu Suza, baza za vinske podrume.', 45.7857, 18.782),
  ('camp-zaton-resort', null, 'zadar', null, 'Zaton Holiday Resort', 'campsite', 'Veliki kamp u Ninu (Zaton) s golemim bazenskim kompleksom i pješčanom plažom.', 44.2258, 15.1708),
  ('camp-falkensteiner-zadar', null, 'zadar', null, 'Falkensteiner Premium Camping Zadar', 'campsite', 'Luksuzni kamp u Zadru (Borik), otvoren cijele godine, s wellnessom i bazenom.', 44.1356, 15.2217),
  ('camp-avalona', null, 'zadar', null, 'Aminess Avalona Camping Resort', 'campsite', 'Luksuzni kamp na otoku Pagu (Povljana) sa smještajem uz privatne bazene.', 44.3342, 15.0991),
  ('camp-ljutic', null, 'zadar', null, 'Campsite Ljutić', 'campsite', 'Obiteljski kamp uz more i šljunčanu plažu u Biogradu na Moru.', 43.9314, 15.4356),
  ('camp-stine', null, 'zadar', null, 'Camp Stine', 'campsite', 'Manji kamp u Pakoštanima s hladom borova i izravnim pristupom plaži.', 44.2711, 15.3458),
  ('camp-miocic', null, 'zadar', null, 'Camp Miočić', 'campsite', 'Mirni obiteljski kamp u Rtini kod Zadra, poznat po domaćoj hrani.', 44.2586, 15.2639),
  ('camp-phalaris', null, 'zadar', null, 'Terra Park Phalaris', 'campsite', 'Kamping resort na sjeveru otoka Paga uz kristalno more, s luksuznim parcelama.', 44.5817, 14.8569),
  ('camp-kanic', null, 'zadar', null, 'Camp Kanić', 'campsite', 'Mali mirni kamp u uvali Kanić na Pagu, okružen stoljetnim maslinama.', 44.5956, 14.8694),
  ('camp-spiritos', null, 'zadar', null, 'Terra Park SpiritoS', 'campsite', 'Prostrani kamp na Pagu uz dugu pješčanu plažu s pogledom na Velebit.', 44.4711, 15.0211),
  ('camp-jezera-lovisca', null, 'sibenik-knin', null, 'Kamp Jezera Lovišća (Murter)', 'campsite', 'Kamp u mirnoj uvali na otoku Murteru s plitkim morem i vlastitom marinom.', 43.7917, 15.6111),
  ('camp-dunav-ilok', null, 'vukovar-srijem', null, 'Kamp Dunav (Ilok)', 'campsite', 'Mali ugodni kamp na obali Dunava u Iloku, blizu iločkih vinarija.', 45.2217, 19.3814),
  ('camp-stobrec-split', null, 'split-dalmatia', null, 'Kamp Stobreč Split', 'campsite', 'Kamp na šumovitom poluotoku kraj Splita s dvije šljunčane plaže i wellnessom.', 43.5014, 16.5256),
  ('camp-galeb-omis', null, 'split-dalmatia', null, 'Kamp Galeb (Omiš)', 'campsite', 'Obiteljski kamp na pješčanoj plaži u Omišu, uz ušće rijeke Cetine.', 43.4397, 16.6811),
  ('camp-belvedere-trogir', null, 'split-dalmatia', null, 'Kamp Belvedere (Seget Vranjica)', 'campsite', 'Terasasti kamp kod Trogira s pogledom na jadranske otoke i bazenom.', 43.5186, 16.2042),
  ('camp-bunja-brac', null, 'split-dalmatia', null, 'Boutique Camping Bunja (Brač)', 'campsite', 'Butik kamp u Supetru na Braču, intiman smještaj pod borovima uz more.', 43.3756, 16.5369),
  ('camp-amadria-trogir', null, 'split-dalmatia', null, 'Camping Amadria Park Trogir', 'campsite', 'Kamp u Segetu Vranjici kod Trogira, uz borovu šumu i šljunčanu plažu.', 43.5133, 16.2169),
  ('camp-lanterna', null, 'istria', null, 'Valamar Camping Lanterna', 'campsite', 'Jedan od najvećih europskih kampova, kod Poreča, s vodenim parkom i glampingom.', 45.2991, 13.5911),
  ('camp-park-umag', null, 'istria', null, 'Camping Park Umag', 'campsite', 'Obiteljski kamp na sjeveru Istre s bazenskim kompleksom i dugom uređenom plažom.', 45.3706, 13.5469),
  ('camp-istra-funtana', null, 'istria', null, 'Istra Premium Camping Resort (Funtana)', 'campsite', 'Luksuzni kamp kod Funtane s privatnim bazenima i aquaparkom Aquamar.', 45.1764, 13.5991),
  ('camp-mon-perin', null, 'istria', null, 'Camping Resort Mon Perin (Bale)', 'campsite', 'Kamp kod povijesnog mjesta Bale s dugom netaknutom obalom i paleo-parkom.', 45.0114, 13.7253),
  ('camp-san-servolo', null, 'istria', null, 'San Servolo Wellness Camping (Buje)', 'campsite', 'Butik wellness kamp u unutrašnjosti Istre kod Buja, s privatnim hidromasažama.', 45.4142, 13.6211),
  ('camp-sirena-novigrad', null, 'istria', null, 'Aminess Planet Camping Sirena', 'campsite', 'Uređen kamp u Novigradu uz more, u naručju borove šume.', 45.3183, 13.5769),
  ('camp-maravea', null, 'istria', null, 'Aminess Planet Camping Maravea Resort', 'campsite', 'Kamping resort u Novigradu okružen vinogradima i maslinicima.', 45.3458, 13.5414),
  ('camp-kanegra', null, 'istria', null, 'FKK Naturist Campsite Kanegra', 'campsite', 'Tradicionalni naturistički kamp u skrivenoj uvali Kanegra kod Umaga.', 45.4864, 13.5635),
  ('camp-savudrija', null, 'istria', null, 'Campsite Savudrija', 'campsite', 'Mirni kamp u Savudriji, podno najstarijeg aktivnog svjetionika na Jadranu.', 45.4864, 13.5111),
  ('camp-vestar', null, 'istria', null, 'Campsite Veštar (Rovinj)', 'campsite', 'Kamp u mirnoj uvali s pješčanom plažom kod Rovinja, idealan za obitelji.', 45.0531, 13.6811),
  ('camp-santa-marina', null, 'istria', null, 'Boutique Campsite Santa Marina', 'campsite', 'Mali luksuzni kamp na poluotoku Lanterna kod Tar-Vabrige, s glampingom.', 45.2861, 13.5936),
  ('camp-valalta', null, 'istria', null, 'Naturist Camping Valalta', 'campsite', 'Nagrađivani naturistički kamp na ulazu u Limski zaljev kod Rovinja.', 45.1217, 13.6264),
  ('camp-marina-labin', null, 'istria', null, 'Valamar Camping Marina (Labin)', 'campsite', 'Specijalizirani ronilački kamp u Svetoj Marini kod Labina s bogatim podmorjem.', 45.0256, 14.1611),
  ('camp-bijela-uvala', null, 'istria', null, 'Camping Bijela Uvala', 'campsite', 'Veliki kamp u Funtani (Zelena laguna) kod Poreča, s više bazena i plažama.', 45.1956, 13.5969),
  ('camp-polidor', null, 'istria', null, 'Polidor Camping Resort', 'campsite', 'Obiteljski kamp u Funtani, otvoren cijele godine, s opuštenim ugođajem.', 45.1991, 13.5978),
  ('camp-val-saline', null, 'istria', null, 'Camp Val Saline', 'campsite', 'Kamp uz uvalu Saline kod Rovinja, s uređenim parcelama tik uz more.', 45.1169, 13.6311),
  ('camp-banki-green', null, 'istria', null, 'Campsite Banki Green Istrian Village', 'campsite', 'Mali kontinentalno-mediteranski wellness kamp u unutrašnjosti Istre.', 45.2411, 13.7656),
  ('camp-nevio-orebic', null, 'dubrovnik-neretva', null, 'Kamp Nevio (Orebić)', 'campsite', 'Obiteljski kamp u Orebiću na Pelješcu, na terasama uz pješčanu plažu.', 42.9833, 17.1611),
  ('camp-lupis-loviste', null, 'dubrovnik-neretva', null, 'Kamp Lupis (Lovište)', 'campsite', 'Mali ekološki butik kamp u uvali Lovište na zapadnom vrhu Pelješca.', 43.0233, 17.0314),
  ('camp-lavanda-orebic', null, 'dubrovnik-neretva', null, 'Kamp Lavanda (Orebić)', 'campsite', 'Kamp kod Orebića s pogledom na Korčulu, među maslinicima i lavandom.', 42.9811, 17.1511),
  ('camp-toplice-svetimartin', null, 'medimurje', null, 'Kamp Toplice Sveti Martin', 'campsite', 'Moderni kamp uz Terme Sveti Martin, u zelenom brežuljkastom Međimurju.', 46.5056, 16.3683),
  ('mtn-strahinjscica', null, 'krapina-zagorje', null, 'Strahinjščica', 'mountain', null, 46.1833, 15.8667),
  ('mtn-ivanscica', null, 'krapina-zagorje', null, 'Ivanščica', 'mountain', null, 46.1833, 16.1167),
  ('mtn-kalnik', null, 'koprivnica-krizevci', null, 'Kalnik', 'mountain', null, 46.1311, 16.4633),
  ('mtn-moslavacka-gora', null, 'sisak-moslavina', null, 'Moslavačka gora', 'mountain', null, 45.6214, 16.7378),
  ('mtn-klek', null, 'karlovac', null, 'Klek', 'mountain', null, 45.2581, 15.1436),
  ('mtn-snjeznik', null, 'primorje-gorski-kotar', null, 'Snježnik', 'mountain', null, 45.4419, 14.5828),
  ('mtn-psunj', null, 'pozega-slavonia', null, 'Psunj (Brezovo Polje)', 'mountain', null, 45.3986, 17.3017),
  ('mtn-dilj-gora', null, 'brod-posavina', null, 'Dilj gora', 'mountain', null, 45.2833, 18.0167),
  ('mtn-dinara', null, 'sibenik-knin', null, 'Dinara (Sinjal)', 'mountain', null, 44.046, 16.414),
  ('mtn-vidova-gora', null, 'split-dalmatia', null, 'Vidova gora (Brač)', 'mountain', null, 43.2806, 16.6375),
  ('mtn-sveti-ilija', null, 'dubrovnik-neretva', null, 'Sveti Ilija (Pelješac)', 'mountain', null, 42.9972, 17.1611),
  ('mtn-mohokos', null, 'medimurje', null, 'Mohokos', 'mountain', null, 46.4172, 16.3542)
on conflict (id) do nothing;

-- Finalize the poi_progress → pois foreign key now that pois is populated:
-- drop any saved progress that points at a POI no longer in the data, then validate the
-- constraint (added NOT VALID in schema.sql). Safe to re-run.
delete from public.poi_progress
  where poi_id not in (select id from public.pois);
alter table public.poi_progress validate constraint poi_progress_poi_id_fkey;
