import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // Enforces using interfaces for all object definitions project-wide
  {
    rules: {
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `pnpm gen:types` — never hand-edited, follows Supabase's codegen style
    // (e.g. `type Database = …`), so project style rules don't apply.
    "src/lib/supabase/database.types.ts",
  ]),
]);

export default eslintConfig;
